namespace BlogDoFT.Libs.ResultPattern;

public static class MapExtension
{
    /// <summary>
    /// Maps a <see cref="Result{TValue}"/> into a value of type <typeparamref name="TReturn"/>,
    /// applying the appropriate function depending on whether it is a success or failure.
    /// </summary>
    /// <typeparam name="TValue">The type of the contained value when successful.</typeparam>
    /// <typeparam name="TReturn">The type returned by the mapping functions.</typeparam>
    /// <param name="result">The result to transform.</param>
    /// <param name="onSuccess">Function applied to the success value.</param>
    /// <param name="onFailure">Function applied to the failure value.</param>
    /// <returns>
    /// A value of type <typeparamref name="TReturn"/> generated by either delegate.
    /// </returns>
    /// <remarks>
    /// Useful for converting the inner success (or failure) value into a different type
    /// while preserving the semantics of success or failure.
    /// </remarks>
    public static TReturn Map<TValue, TReturn>(
        this Result<TValue> result,
        Func<TValue, TReturn> onSuccess,
        Func<Failure, TReturn> onFailure) =>
        result.IsSuccess ? onSuccess(result.Value!) : onFailure(result.Failure!);

    /// <summary>
    /// Maps a <see cref="Result{TValue}"/> into a value of type <typeparamref name="TReturn"/>,
    /// applying the appropriate function depending on whether it is a success or failure.
    /// </summary>
    /// <typeparam name="TValue">The type of the contained value when successful.</typeparam>
    /// <typeparam name="TReturn">The type returned by the mapping functions.</typeparam>
    /// <param name="task">The task result to transform.</param>
    /// <param name="onSuccess">Function applied to the success value.</param>
    /// <param name="onFailure">Function applied to the failure value.</param>
    /// <returns>
    /// A value of type <typeparamref name="TReturn"/> generated by either delegate.
    /// </returns>
    /// <remarks>
    /// Useful for converting the inner success (or failure) value into a different type
    /// while preserving the semantics of success or failure.
    /// </remarks>
    public static async Task<TReturn> MapAsync<TValue, TReturn>(
        this Task<Result<TValue>> task,
        Func<TValue, TReturn> onSuccess,
        Func<Failure, TReturn> onFailure)
    {
        var result = await task.ConfigureAwait(false);
        return result.IsSuccess
            ? onSuccess(result.Value!)
            : onFailure(result.Failure!);
    }
}
