// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Api.Features.Sales.Infrastructure;

#nullable disable

namespace WebApi.Api.Migrations
{
    [DbContext(typeof(SalesDbContext))]
    [Migration("20251105042952_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("WebApi.Api.Features.Sales.Infrastructure.Models.SaleItemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<decimal>("Discount")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("discount");

                    b.Property<string>("ProductDescription")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("product_description");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT")
                        .HasColumnName("quantity");

                    b.Property<int>("SaleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sale_id");

                    b.Property<decimal>("UnitValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("unit_value");

                    b.HasKey("Id")
                        .HasName("pk_sale_item");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_sale_item__product_id");

                    b.HasIndex("SaleId")
                        .HasDatabaseName("ix_sale_item__sale_id");

                    b.ToTable("sale_item", (string)null);
                });

            modelBuilder.Entity("WebApi.Api.Features.Sales.Infrastructure.Models.SaleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("TEXT")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("client_name");

                    b.Property<int>("Installments")
                        .HasColumnType("INTEGER")
                        .HasColumnName("installments");

                    b.Property<Guid>("NavigationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("navigation_id");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("payment_method");

                    b.HasKey("Id")
                        .HasName("pk_sale");

                    b.HasIndex("NavigationId")
                        .IsUnique()
                        .HasDatabaseName("ux_sale_navigation_id");

                    b.ToTable("sale", (string)null);
                });

            modelBuilder.Entity("WebApi.Api.Features.Sales.Infrastructure.Models.SaleItemModel", b =>
                {
                    b.HasOne("WebApi.Api.Features.Sales.Infrastructure.Models.SaleModel", "Sale")
                        .WithMany("Items")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sale_item__sale_id");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("WebApi.Api.Features.Sales.Infrastructure.Models.SaleModel", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
